version: "3"

services:
  mongodb:
    image: mongo

  controller:
    build: ./controller
    command: yarn dev
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mongodb
      - DATABASE_NAME=iot-server
    depends_on:
      - mongodb
    volumes:
      - ./controller:/usr/app
      - /usr/app/node_modules
